### ISSUE TITLE
Migration from v201402 to 201409

### ISSUE THREAD

**Issue by vig92** [googleads/aw-reporting#105]
We missed the sunset date for v201402 somehow. Now we need to migrate our system from v201402 to v201409. 
Changes for v201406 to v201409 migration alone is available in this repo. But changes for v201402 to v201406 are not.
Request help for the same.

**Comment by gustavo-moreira** [comment]
Hi there,

If you take a look at the commit history, you will find the older commits containing the migrations from older version. This one in particular might help you:
