### ISSUE TITLE
Keywordless reports

### ISSUE THREAD

**Issue by dancsvfd** [googleads/aw-reporting#109]
Are there any plans to include the KEYWORDLESS_QUERY_REPORT on aw-reports? 

If not, how could I add it myself?

thanks

dayres

**Comment by gustavo-moreira** [comment]
Hi,

This quarter we don't have any new feature planned for AwReporting besides the version migration.

You can either create an Issue in GitHub and wait for someone accept it and implement it in the project (should happen after March), or if you want to implement it yourself, check how the other reports are implemented. Basically:
- Create a class in the report model package that contains all the fields available in the report you want to add. Remember to extend one of the available super classes, so you get a lot of fields that are common across reports.
- In your new class, add the CSV mapping annotations so the CSV parser can map between the field in the Report definition, the CSV file and the Java entity.
- Add the report key to the class, also with an annotation.
- Create a unit test based on the other examples. The base unit test will check for DB mapping, and will require a CSV downloaded from the report API, to test the CSV mapping.
- Add the report definition to the properties file.
- Run the project and make sure the table was created, and the report is being downloaded.

All the DB configuration is done automatically.

The best way to do it, is to take a look at the other classes available. It is a very straight forward process.

Hope this helps.

**Comment by gustavo-moreira** [comment]
This was added to the backlog.
We will be checking the possibility to add this in the project.
