### ISSUE TITLE
Unable to refresh OAuth token

### ISSUE THREAD

**Issue by vig92** [googleads/aw-reporting#112]
We've scheduled AWReport download on a server. Getting the following Error :
"**ERROR** Credential could not be refreshed, we need a new OAuth2 Token
**ACTION REQUIRED** Paste this url in your browser and authenticate using your **AdWords Admin Email**:
<URL>
Type the code you received on the web page here:"
Need help figuring out where exactly to use the code that is generated.

**Comment by gustavo-moreira** [comment]
Hi vig92,

Sorry, but I didn't understand the problem.
Did you copied the URL displayed on the console, then pasted on the browser and logged in with the account that you created the clientId and secret?

After that you should get a token back, and paste on the same console running AwReporting.
Even after doing that, did you still get an error?

**Comment by chenzhuo914** [comment]
Closing this issue since there's no more inquiry for 2 months. Please feel free to reopen it when needed.
