### ISSUE TITLE
Missing files running the aw-reporting-server

### ISSUE THREAD

**Issue by rakuraku678** [googleads/aw-reporting#113]
Hi, when I run the aw-reporting-server and I go to http://localhost:8081/awrc/index.html, It keeps loading forever and in the meantime the console throws me:

Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8081/awrc/app/controllers/onboardingcontroller.js 
http://localhost:8081/awrc/app/controllers/nvsptecontroller.js

Where can I get those files? Is that the reason the loading screen keeps forever loading or maybe there is another reason?

Greetings,
Diego

**Comment by gustavo-moreira** [comment]
Hi Diego,

Sorry for the inconvenience, but we are still working on this project and
it was not "officially" released yet.
We are planning some updates to take place in the near future, but
meanwhile I will check if there is any quick fix for this.

Thanks.

**Comment by joeltoby** [comment]
Hi Diego,

Sorry about this.  References to those files should actually have been removed.  The issue should now be resolved.  Please let us know if it isn't.
