### ISSUE TITLE
Error in mvn clean install

### ISSUE THREAD

**Issue by dancsvfd** [googleads/aw-reporting#122]
I am trying to update the aw-report to use with the new API version:
So I downloaded the new files and tried to run $ mvn clean install eclipse:eclipse and got some errors like this:

testFormatDateFullMonthYear(com.google.api.ads.adwords.awreporting.util.TemplateStringsUtilTest)  Time elapsed: 0.001 sec  <<< FAILURE!
junit.framework.ComparisonFailure: expected:<Mar[ch] 2014> but was:<Mar[þo] 2014>

It looks like it is getting the name of the month in Portuguese (my native lang) instead of the expected value in english.. As I don't even know where are those values coming from, I have no idea what to do..

I am still using the older API version, which I know will stop working real soon

How can I fix this problem?

Thanks a lot,

dancsvfd

**Comment by dancsvfd** [comment]
How can I provide you some logs or debugs that can help identify the problem?

**Comment by mauromazzucco** [comment]
This happens to me everytime i update aswell(brazilian too), what i do is
just skip the tests, you can use this flag -Dmaven.test.skip=true
So run:
mvn clean install eclipse:eclipse -Dmaven.test.skip=true
and
 mvn compile dependency:copy-dependencies package Dmaven.test.skip=true

2015-03-31 17:09 GMT-03:00 dancsvfd <notifications@github.com>:

**Comment by dancsvfd** [comment]
Thank you very much Mauro, your flags did the trick and I think AwReporting is running normally now.
Are we missing something or taking some extra risks by avoiding those tests? Thanks again

**Comment by gustavo-moreira** [comment]
Hi,

skipping the tests is always risky since we are not covering how the basic
functionality is working, so we are working on a solution to the problem.

In summary, it is just a matter of setting the Locale to English before
running the test, and setting it back again to the JVM default after the
test is done, but we are just making sure that this will affect only this
test case.

Thanks.

**Comment by gustavo-moreira** [comment]
Hi,

the build was fixed for all languages.

Thanks.
