### ISSUE TITLE
numberOfActiveCampaigns is always 0

### ISSUE THREAD

**Issue by yepelinux** [googleads/aw-reporting#123]
I always get "numberOfActiveCampaigns: 0" when using kratu's JSON REST in  
/mcc/xxmccaccount/kratu?dateStart=20150101&dateEnd=20150401

no matter what period i try.

This is the hole json i get for one account:

{
externalCustomerId: 50281XXXXX,
topAccountId: 84354XXXXX,
accountName: "Uni Client",
currencyCode: "ARS",
dateTimeZone: "America/Argentina/Buenos_Aires",
accountActive: "Yes",
totalClicksSearch: 241705,
impressionsSearch: 7676746,
ctrSearch: 2.89,
averageCpcSearch: 2.61,
averageCpmSearch: 79.88,
averagePositionSearch: 2.85,
totalClicksDisplay: 665247,
impressionsDisplay: 23409716,
ctrDisplay: 2.65,
averageCpcDisplay: 0.03,
averageCpmDisplay: 8.26,
averagePositionDisplay: 0.95,
spend: 876115.44,
conversions: 25055,
elegibleImpressionsSearch: 35380697.32,
elegibleImpressionsDisplay: 205350406.27,
lostImpressionsDueToBudgetSearch: 12124227.59,
lostImpressionsDueToBidAdRankSearch: 15579729.97,
lostImpressionsDueToBudgetDisplay: 141039598.5,
lostImpressionsDueToBidAdRankDisplay: 44241814.08,
numberOfActiveCampaigns: 0,
numberOfActiveAdGroups: 526.43,
numberOfActiveAds: 762.51,
numberOfPositiveActiveKeywords: 0,
numberOfActiveBroadMatchingKeywords: 0,
numberOfActivePhraseMatchingKeywords: 0,
numberOfActiveExactMatchingKeywords: 0,
numberOfNegativeActiveKeywords: 902.09,
numberOfCampaignNegativeActiveKeywords: 902.09,
numberOfAdGroupNegativeActiveKeywords: 0,
numberOfActiveGoodQualityScoreKeywords: 0,
numberOfActiveAverageQualityScoreKeywords: 0,
numberOfActivePoorQualityScoreKeywords: 0,
numberOfCampaignsWithCallExtensionEnabled: 0,
numberOfCampaignsWithLocationExtensionEnabled: 0,
numberOfCampaignsWithSiteLinksEnabled: 0,
weightedAverageKeywordPosition: 0,
weightedAverageQualityScore: 0,
sumBudget: 1908421,
accountSuspended: false,
numberOfAdgroupsWithoneActiveAd: 258.08,
numberOfAdgroupsWithTwoActiveAds: 114.42,
numberOfDisapprovedAds: 0
}

**Comment by gustavo-moreira** [comment]
Some more info:

numberOfActiveCampaigns: 0,
numberOfPositiveActiveKeywords: 0,
numberOfActiveBroadMatchingKeywords: 0,
numberOfActivePhraseMatchingKeywords: 0,
numberOfActiveExactMatchingKeywords: 0,
numberOfAdGroupNegativeActiveKeywords: 0,
numberOfActiveGoodQualityScoreKeywords: 0,
numberOfActiveAverageQualityScoreKeywords: 0,
numberOfActivePoorQualityScoreKeywords: 0,
numberOfCampaignsWithCallExtensionEnabled: 0,
numberOfCampaignsWithLocationExtensionEnabled: 0,
numberOfCampaignsWithSiteLinksEnabled: 0,
weightedAverageKeywordPosition: 0,
weightedAverageQualityScore: 0,

**Comment by joeltoby** [comment]
Fix for this issue will be pushed with the v201502 upgrade
