### ISSUE TITLE
cpcbid not working?

### ISSUE THREAD

**Issue by dancsvfd** [googleads/aw-reporting#127]
I am trying to get CpcBid from KEYWORDS_PERFORMANCE_REPORT but with no luck.

Actually, I can't even find the CpcBid column on the mysql table AW_ReportKeyword (athough MAX_CPC is there, with all nulls).

I see no error messages when I run "java -Xmx1G -jar ..." 

I couldn't find out why this is happening. Any ideas?

follows the whole field list I am getting:
"AccountTimeZoneId,AdNetworkType1,AdNetworkType2,Device,ExternalCustomerId,Date,DayOfWeek,Week,Month,MonthOfYear,Quarter,Year,AccountDescriptiveName,Cost,Clicks,Impressions,ConversionsManyPerClick,Conversions,ConversionRate,ConversionValue,AverageCpc,AveragePosition,AccountCurrencyCode,Id,QualityScore,KeywordMatchType,KeywordText,DestinationUrl,AdGroupId,CampaignId,Status,IsNegative,CampaignName,CpcBid,SearchImpressionShare,SearchRankLostImpressionShare"

**Comment by gustavo-moreira** [comment]
Hi Dan,

The CpcBid field in the report is the MAX_CPC in the MySQL table. I checked the mapping between the report and the entity, and everything seems correct.
Did you try to download the report directly from the API to see if this is a problem at the service level?
(You can check the downloaded CSV files for the reports)

Thanks.

**Comment by chenzhuo914** [comment]
I've verified that I am able to pull CpcBid in KEYWORDS_PERFORMANCE_REPORT, and see the non-null values in the MAX_CPC column in the database table "AW_ReportKeyword".

**Comment by dancsvfd** [comment]
I've re-downloaded the whole project and compiled it again. It is working fine now. Thank you guys  a lot!
