### ISSUE TITLE
Unable to run AwReporting.java When I try to run this file in Eclipse IDE it gives some messages [ERROR|com.google.api.ads.adwords.awreporting.AwReporting|AwReporting] Missing required option: 'file'

### ISSUE THREAD

**Issue by osingh** [googleads/aw-reporting#128]

**Comment by chenzhuo914** [comment]
Hi osingh, the error message is very clear: you must provide "file" option when running AwReporting.java.

In Eclipse IDE, you should choose "Run" -> "Run Configurations...", then in "Arguments" tab, provide argument like "-file aw-reporting/src/main/resources/aw-report-sample.properties".

**Comment by osingh** [comment]
Hi Chenzhuo, Thanks a lot for reply. 
You are right this works for me. But now I am getting another messages i.e "Configuration incomplete. Missing options for command line."  I am new in Google AwReporting, so please let me know how to configure that AwReporting.java and how to run it. 

Thanks,
Om Singh

**Comment by chenzhuo914** [comment]
Hi Om, this error means you didn't provide all the required arguments, I think most probably you missed "startDate" and "endDate".

You can refer to the instructions in this project's first page https://github.com/googleads/aw-reporting, where you can see a sample command line:
java -Xmx1G -jar aw-reporting.jar -startDate YYYYMMDD -endDate YYYYMMDD -file <file>

**Comment by gustavo-moreira** [comment]
I am closing this issue.
Please, make sure to read the instructions on how to run AwReporting and add the correct properties to the Eclipse IDE for further usage.
Keep in mind that we don't support the execution from inside Eclipse, so you might encounter other issues later.

Thanks.

**Comment by osingh** [comment]
Thanks Chenzhuo..!!!
