### ISSUE TITLE
Bid Modifier (Mobile, Ad Schedule, Geolocation)

### ISSUE THREAD

**Issue by israelramos** [googleads/aw-reporting#130]
I´m trying getting those fields in the API but i don´t know which report/field to use.  Someone could help me with this?

**Comment by markbowyer** [comment]
Hi,

I believe they're all types of Criteria, and indeed the Criteria
Performance Report has a Bid Modifier field -
https://developers.google.com/adwords/api/docs/appendix/reports#criteria

Does that help?
Mark

**Comment by chenzhuo914** [comment]
Close this issue since no more inquiry for quite a while.
