### ISSUE TITLE
Empty headline for dynamic search ads

### ISSUE THREAD

**Issue by Timmeh74** [googleads/aw-reporting#136]
Hi!

For the dynamically created ad headlines of the new dynamic search ads, the database field **HEADLINE** in **AW_ReportAd** is empty. Is it possible to add a placeholder similar to {Keyword:mykeyword} to the database?

Thanks!

Regards,
Tim Bongers

**Comment by chenzhuo914** [comment]
Hi Tim, I doubt we should implement this specific feature for your requirement, whereas other users may not have the same requirement or even have different ones. We want to make aw-reporting generic and simple, by just downloading the "raw" report data and persisting it on local DB.

I think you can implement some post-processing logic yourself, to change HEADLINE values to your intended placeholder for dynamic search ads.

**Comment by Timmeh74** [comment]
Hi! Thanks for your feedback. Is there an easy way to detect dynamic search ads from the AwReports database? Or is it save to assume that an empty headline means that we are dealing with a dynamic search ad?

**Comment by chenzhuo914** [comment]
You can download the AdType field, where dynamic search ads will return value "DYNAMIC_SEARCH_AD". Please refer to the report doc for more details: https://developers.google.com/adwords/api/docs/appendix/reports/ad-performance-report#adtype

Also, if you want to pull detailed information about dynamic search ads performance, you can use other reports, as described in this guide: https://developers.google.com/adwords/api/docs/guides/dynamic-search-ads#reporting

**Comment by Timmeh74** [comment]
Thanks a lot, that's all I need. Closing this issue :)

**Comment by Timmeh74** [comment]
PS: Is it possible that the AdType field is not listed in the "Available Fields" of the AwReporting properties file? I can't seem to find it there.

**Comment by chenzhuo914** [comment]
You are right, we missed it in the properties file. I will add it in next code commit.

Actually the "Available fields" in properties file are just for reference (note they are all commented), please use the official doc (https://developers.google.com/adwords/api/docs/appendix/reports) as ultimate answer. :)
