### ISSUE TITLE
Write filetype Booleans need removing from code

### ISSUE THREAD

**Issue by markbowyer** [googleads/aw-reporting#138]
Some Booleans were left in when the PDF/HTML code removal from the main code took place.  These need tidying.

**Comment by gustavo-moreira** [comment]
Some more details:

This is the file
https://github.com/googleads/aw-reporting/blob/master/aw-reporting/src/main/java/com/google/api/ads/adwords/awreporting/exporter/ReportExporter.java

The booleans are:
        Boolean writeHtml = false;
     
        Boolean writePdf = false;
       
        Boolean writeDriveDoc = false;

**Comment by markbowyer** [comment]
Done
