### ISSUE TITLE
Video Campaigns Full Report

### ISSUE THREAD

**Issue by scanything** [googleads/aw-reporting#145]
Hey,

Is there an option to add the Video Campaigns Full Report available via Interface?
When in the "Video Campaigns Page" you can download it via the Bulk Upload -> All data and statistics.

Thanks
![adwords-all-statistics](https://cloud.githubusercontent.com/assets/11459579/8497544/e20d8ae2-2186-11e5-881e-f701809b5c44.png)
![adwords-bulk-upload](https://cloud.githubusercontent.com/assets/11459579/8497543/e20cdaa2-2186-11e5-89f8-d42ef59aa253.png)

**Comment by gustavo-moreira** [comment]
Hi,

Right now AwReporting only supports the regular report data from the video campaigns.
We are still running this as an experiment, so we don't have any immediate plans to include new features to it, but we will take your question as a possible feature request for the next iteration.

If you want, you can add these fields to the ReportVideoCampaign.java class, and as long as the mapping is correct, AwReporting should import the additional data without any other further changes.

Thanks.

**Comment by scanything** [comment]
The report I'm talking about includes several objects such as campaigns, ads, targeting groups, targets etc.
Each object has a special section for it in the report.
For example:
for campaigns you have a row such as:
Input campaigns here 

for ads you have a row such as:
Input ads here 

Can this even be parsed?

Thanks

**Comment by gustavo-moreira** [comment]
Hi,

It has to follow the default CSV file format to be parsed by AwReporting, otherwise you would need to implement an specific parser for it, which is beyond the project's scope.
Thanks.
