### ISSUE TITLE
Empty accountIdsFile

### ISSUE THREAD

**Issue by muhlegg** [googleads/aw-reporting#146]
It seems like an empty accountIdsFile triggers aw-reporting to fetch all mcc accounts? Is this really wanted?

**Comment by chenzhuo914** [comment]
Yes, this is by design, we consider empty accountIdsFile as skipping this option, so it falls back to fetch all accounts under the specified MCC.

Anyway, you have the control - if you don't want to fetch all accounts, just provide some non-empty accountIdFile. :)

**Comment by muhlegg** [comment]
Ok thanks for the info. Did not know this until yesterday when one of our processes generating the proper accountsfile failed and awr fetched data for several thousand accounts instead of a few hundred :)

**Comment by chenzhuo914** [comment]
I see, thanks for your clarification! In that case, you may want to add a post-check to make sure the accountIdsFile is properly generated (at least non empty) before invoking awr. :)
