### ISSUE TITLE
Hibernate batch processing

### ISSUE THREAD

**Issue by irfany** [googleads/aw-reporting#148]
Hi,

Thanks for this great library.

Just one thing - should line  89 of SqlReportEntitiesPersister.java

be     if (batchFlush % BATCH_SIZE == 0) {

rather than     if (batchFlush == BATCH_SIZE) {

Thanks
Irfan

**Comment by chenzhuo914** [comment]
Hi Irfan, thanks for reporting this issue. I think it's indeed a bug.

Alternative fix is to reset "batchFlush" to zero after line 91. We will fix it asap.
