### ISSUE TITLE
Automatically generate entry IDs for various reports

### ISSUE THREAD

**Issue by chenzhuo914** [googleads/aw-reporting#152]
One common problem (especially for beginners) is that, after users selecting fields for some reports, he/she forgot to add all segment fields into the setId() method, so the report downloading might fail and abort due to "duplicate ID" error.

I think we can solve this problem, by getting the behaviors of all chosen fields from ReportDefinitionService , and automatically including Segment fields' values into setId() method.

**Comment by gustavo-moreira** [comment]
I am closing this one, because we are handling the IDs in the new report entity generation module.
