### ISSUE TITLE
Can't compile aw-reporting-server

### ISSUE THREAD

**Issue by jawb** [googleads/aw-reporting#156]
$:~/aw-reporting/aw-reporting-server# mvn clean install eclipse:eclipse
[INFO] Scanning for projects...
[INFO] Searching repository for plugin with prefix: 'eclipse'.
[INFO] ------------------------------------------------------------------------
[INFO] Building aw-reporting-server
[INFO]    task-segment: [clean, install, eclipse:eclipse]
[INFO] ------------------------------------------------------------------------
[INFO] [clean:clean {execution: default-clean}]
Downloading: http://repo1.maven.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.pom
7K downloaded  (maven-resources-plugin-2.6.pom)
Downloading: http://repo1.maven.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.jar
28K downloaded  (maven-resources-plugin-2.6.jar)
Downloading: http://repo1.maven.org/maven2/org/codehaus/plexus/plexus-utils/2.0.5/plexus-utils-2.0.5.pom
3K downloaded  (plexus-utils-2.0.5.pom)
Downloading: http://repo1.maven.org/maven2/org/codehaus/plexus/plexus/2.0.6/plexus-2.0.6.pom
16K downloaded  (plexus-2.0.6.pom)
Downloading: http://repo1.maven.org/maven2/org/apache/maven/shared/maven-filtering/1.1/maven-filtering-1.1.pom
5K downloaded  (maven-filtering-1.1.pom)
Downloading: http://maven.restlet.org/org/codehaus/plexus/plexus-interpolation/1.12/plexus-interpolation-1.12.pom
[INFO] Unable to find resource 'org.codehaus.plexus:plexus-interpolation:pom:1.12' in repository maven-restlet (http://maven.restlet.org)
Downloading: http://repo1.maven.org/maven2/org/codehaus/plexus/plexus-interpolation/1.12/plexus-interpolation-1.12.pom
889b downloaded  (plexus-interpolation-1.12.pom)
Downloading: http://maven.restlet.org/org/sonatype/plexus/plexus-build-api/0.0.4/plexus-build-api-0.0.4.pom
[INFO] Unable to find resource 'org.sonatype.plexus:plexus-build-api:pom:0.0.4' in repository maven-restlet (http://maven.restlet.org)
Downloading: http://repo1.maven.org/maven2/org/sonatype/plexus/plexus-build-api/0.0.4/plexus-build-api-0.0.4.pom
2K downloaded  (plexus-build-api-0.0.4.pom)
Downloading: http://maven.restlet.org/org/sonatype/spice/spice-parent/10/spice-parent-10.pom
[INFO] Unable to find resource 'org.sonatype.spice:spice-parent:pom:10' in repository maven-restlet (http://maven.restlet.org)
Downloading: http://repo1.maven.org/maven2/org/sonatype/spice/spice-parent/10/spice-parent-10.pom
2K downloaded  (spice-parent-10.pom)
Downloading: http://maven.restlet.org/org/sonatype/forge/forge-parent/3/forge-parent-3.pom
[INFO] Unable to find resource 'org.sonatype.forge:forge-parent:pom:3' in repository maven-restlet (http://maven.restlet.org)
Downloading: http://repo1.maven.org/maven2/org/sonatype/forge/forge-parent/3/forge-parent-3.pom
4K downloaded  (forge-parent-3.pom)
Downloading: http://repo1.maven.org/maven2/org/codehaus/plexus/plexus-utils/2.0.5/plexus-utils-2.0.5.jar
Downloading: http://maven.restlet.org/org/sonatype/plexus/plexus-build-api/0.0.4/plexus-build-api-0.0.4.jar
Downloading: http://repo1.maven.org/maven2/org/apache/maven/shared/maven-filtering/1.1/maven-filtering-1.1.jar
42K downloaded  (maven-filtering-1.1.jar)
217K downloaded  (plexus-utils-2.0.5.jar)
[INFO] Unable to find resource 'org.sonatype.plexus:plexus-build-api:jar:0.0.4' in repository maven-restlet (http://maven.restlet.org)
Downloading: http://repo1.maven.org/maven2/org/sonatype/plexus/plexus-build-api/0.0.4/plexus-build-api-0.0.4.jar
6K downloaded  (plexus-build-api-0.0.4.jar)
[INFO] [resources:copy-resources {execution: copy-resources}]
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 85 resources
[INFO] [resources:resources {execution: default-resources}]
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 31 resources
[INFO] Copying 85 resources
[INFO] Copying 6 resources
[INFO] snapshot com.google.api-ads:aw-reporting-model:1.8.0-SNAPSHOT: checking for updates from maven-restlet
[INFO] snapshot com.google.api-ads:aw-reporting:1.8.0-SNAPSHOT: checking for updates from maven-restlet
Downloading: http://maven.restlet.org/log4j/log4j/1.2.16/log4j-1.2.16.pom
[INFO] Unable to find resource 'log4j:log4j:pom:1.2.16' in repository maven-restlet (http://maven.restlet.org)
Downloading: http://repo1.maven.org/maven2/log4j/log4j/1.2.16/log4j-1.2.16.pom
19K downloaded  (log4j-1.2.16.pom)
Downloading: http://maven.restlet.org/org/restlet/jse/org.restlet/2.2.0/org.restlet-2.2.0.pom
614b downloaded  (org.restlet-2.2.0.pom)
Downloading: http://maven.restlet.org/org/restlet/jse/org.restlet.parent/2.2.0/org.restlet.parent-2.2.0.pom
9K downloaded  (org.restlet.parent-2.2.0.pom)
Downloading: http://maven.restlet.org/org/restlet/jse/org.restlet.ext.json/2.2.0/org.restlet.ext.json-2.2.0.pom
929b downloaded  (org.restlet.ext.json-2.2.0.pom)
Downloading: http://maven.restlet.org/org/restlet/jse/org.restlet.lib.org.restlet.lib.org.json/2.0/org.restlet.lib.org.restlet.lib.org.json-2.0.pom
507b downloaded  (org.restlet.lib.org.restlet.lib.org.json-2.0.pom)
Downloading: http://maven.restlet.org/org/restlet/jse/org.restlet/2.2.0/org.restlet-2.2.0.jar
Downloading: http://maven.restlet.org/log4j/log4j/1.2.16/log4j-1.2.16.jar
[INFO] Unable to find resource 'log4j:log4j:jar:1.2.16' in repository maven-restlet (http://maven.restlet.org)
Downloading: http://repo1.maven.org/maven2/log4j/log4j/1.2.16/log4j-1.2.16.jar
470K downloaded  (log4j-1.2.16.jar)
668K downloaded  (org.restlet-2.2.0.jar)
Downloading: http://maven.restlet.org/org/restlet/jse/org.restlet.ext.json/2.2.0/org.restlet.ext.json-2.2.0.jar
8K downloaded  (org.restlet.ext.json-2.2.0.jar)
Downloading: http://maven.restlet.org/org/restlet/jse/org.restlet.lib.org.restlet.lib.org.json/2.0/org.restlet.lib.org.restlet.lib.org.json-2.0.jar
47K downloaded  (org.restlet.lib.org.restlet.lib.org.json-2.0.jar)
[INFO] [compiler:compile {execution: default-compile}]
[INFO] Compiling 31 source files to /root/aw-reporting/aw-reporting-server/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /root/aw-reporting/aw-reporting-server/src/main/java/com/google/api/ads/adwords/awreporting/server/util/StorageHelper.java:[22,60] error: cannot find symbol
[ERROR]   symbol:   class ReportCampaignNegativeKeyword
  location: package com.google.api.ads.adwords.awreporting.model.entities
/root/aw-reporting/aw-reporting-server/src/main/java/com/google/api/ads/adwords/awreporting/server/util/StorageHelper.java:[190,14] error: cannot find symbol
[ERROR]   symbol:   class ReportCampaignNegativeKeyword
  location: class StorageHelper
/root/aw-reporting/aw-reporting-server/src/main/java/com/google/api/ads/adwords/awreporting/server/util/StorageHelper.java:[197,14] error: cannot find symbol
[ERROR]   symbol:   class ReportCampaignNegativeKeyword
  location: class StorageHelper
/root/aw-reporting/aw-reporting-server/src/main/java/com/google/api/ads/adwords/awreporting/server/util/StorageHelper.java:[204,14] error: cannot find symbol
[ERROR]   symbol:   class ReportCampaignNegativeKeyword
  location: class StorageHelper
/root/aw-reporting/aw-reporting-server/src/main/java/com/google/api/ads/adwords/awreporting/server/rest/reports/ReportCampaignNegativeKeywordRest.java:[18,60] error: cannot find symbol
[ERROR]   symbol:   class ReportCampaignNegativeKeyword
  location: package com.google.api.ads.adwords.awreporting.model.entities
/root/aw-reporting/aw-reporting-server/src/main/java/com/google/api/ads/adwords/awreporting/server/kratu/KratuCompute.java:[21,60] error: cannot find symbol
[ERROR]   symbol:   class ReportCampaignNegativeKeyword
  location: package com.google.api.ads.adwords.awreporting.model.entities
/root/aw-reporting/aw-reporting-server/src/main/java/com/google/api/ads/adwords/awreporting/server/util/StorageHelper.java:[193,31] error: cannot find symbol
[ERROR]   symbol:   class ReportCampaignNegativeKeyword
  location: class StorageHelper
/root/aw-reporting/aw-reporting-server/src/main/java/com/google/api/ads/adwords/awreporting/server/util/StorageHelper.java:[200,31] error: cannot find symbol
[ERROR]   symbol:   class ReportCampaignNegativeKeyword
  location: class StorageHelper
/root/aw-reporting/aw-reporting-server/src/main/java/com/google/api/ads/adwords/awreporting/server/util/StorageHelper.java:[207,31] error: cannot find symbol
[ERROR]   symbol:   class ReportCampaignNegativeKeyword
  location: class StorageHelper
/root/aw-reporting/aw-reporting-server/src/main/java/com/google/api/ads/adwords/awreporting/server/util/StorageHelper.java:[264,32] error: cannot find symbol
[ERROR]   symbol:   class ReportCampaignNegativeKeyword
  location: class StorageHelper
/root/aw-reporting/aw-reporting-server/src/main/java/com/google/api/ads/adwords/awreporting/server/rest/reports/ReportCampaignNegativeKeywordRest.java:[52,11] error: cannot find symbol
[ERROR]   symbol:   class ReportCampaignNegativeKeyword
  location: class ReportCampaignNegativeKeywordRest
/root/aw-reporting/aw-reporting-server/src/main/java/com/google/api/ads/adwords/awreporting/server/kratu/KratuCompute.java:[390,11] error: cannot find symbol
[INFO] 12 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Compilation failure

/root/aw-reporting/aw-reporting-server/src/main/java/com/google/api/ads/adwords/awreporting/server/util/StorageHelper.java:[22,60] error: cannot find symbol
  symbol:   class ReportCampaignNegativeKeyword
  location: package com.google.api.ads.adwords.awreporting.model.entities
/root/aw-reporting/aw-reporting-server/src/main/java/com/google/api/ads/adwords/awreporting/server/util/StorageHelper.java:[190,14] error: cannot find symbol
  symbol:   class ReportCampaignNegativeKeyword
  location: class StorageHelper
/root/aw-reporting/aw-reporting-server/src/main/java/com/google/api/ads/adwords/awreporting/server/util/StorageHelper.java:[197,14] error: cannot find symbol
  symbol:   class ReportCampaignNegativeKeyword
  location: class StorageHelper
/root/aw-reporting/aw-reporting-server/src/main/java/com/google/api/ads/adwords/awreporting/server/util/StorageHelper.java:[204,14] error: cannot find symbol
  symbol:   class ReportCampaignNegativeKeyword
  location: class StorageHelper
/root/aw-reporting/aw-reporting-server/src/main/java/com/google/api/ads/adwords/awreporting/server/rest/reports/ReportCampaignNegativeKeywordRest.java:[18,60] error: cannot find symbol
  symbol:   class ReportCampaignNegativeKeyword
  location: package com.google.api.ads.adwords.awreporting.model.entities
/root/aw-reporting/aw-reporting-server/src/main/java/com/google/api/ads/adwords/awreporting/server/kratu/KratuCompute.java:[21,60] error: cannot find symbol
  symbol:   class ReportCampaignNegativeKeyword
  location: package com.google.api.ads.adwords.awreporting.model.entities
/root/aw-reporting/aw-reporting-server/src/main/java/com/google/api/ads/adwords/awreporting/server/util/StorageHelper.java:[193,31] error: cannot find symbol
  symbol:   class ReportCampaignNegativeKeyword
  location: class StorageHelper
/root/aw-reporting/aw-reporting-server/src/main/java/com/google/api/ads/adwords/awreporting/server/util/StorageHelper.java:[200,31] error: cannot find symbol
  symbol:   class ReportCampaignNegativeKeyword
  location: class StorageHelper
/root/aw-reporting/aw-reporting-server/src/main/java/com/google/api/ads/adwords/awreporting/server/util/StorageHelper.java:[207,31] error: cannot find symbol
  symbol:   class ReportCampaignNegativeKeyword
  location: class StorageHelper
/root/aw-reporting/aw-reporting-server/src/main/java/com/google/api/ads/adwords/awreporting/server/util/StorageHelper.java:[264,32] error: cannot find symbol
  symbol:   class ReportCampaignNegativeKeyword
  location: class StorageHelper
/root/aw-reporting/aw-reporting-server/src/main/java/com/google/api/ads/adwords/awreporting/server/rest/reports/ReportCampaignNegativeKeywordRest.java:[52,11] error: cannot find symbol
  symbol:   class ReportCampaignNegativeKeyword
  location: class ReportCampaignNegativeKeywordRest
/root/aw-reporting/aw-reporting-server/src/main/java/com/google/api/ads/adwords/awreporting/server/kratu/KratuCompute.java:[390,11] error: cannot find symbol

[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17 seconds
[INFO] Finished at: Tue Jul 28 15:53:42 EDT 2015
[INFO] Final Memory: 33M/80M
[INFO] ------------------------------------------------------------------------

**Comment by gustavo-moreira** [comment]
Hi,

did you try building the main project before compiling the server?

$:~# cd aw-reporting
$:~/aw-reporting# mvn clean install
$:~/aw-reporting# cd aw-reporting-server
$:~/aw-reporting/aw-reporting-server# mvn clean install eclipse:eclipse

It seems like the server is missing the model dependency, which has to be installed in your local repository in order for Maven to find it.
Att.

**Comment by visiperf** [comment]
Hi guys, 

- In : 
aw-reporting-server/src/main/java/com/google/api/ads/adwords/awreporting/server/rest/RestServer.java
Change all *ReportCampaignNegativeKeywordRest* to *ReportCampaignNegativeKeywordsRest* (notice the 's' after *Keyword*)
- In : 
aw-reporting-server/server/src/main/java/com/google/api/ads/adwords/awreporting/server/kratu/KratuCompute.java
Change all *ReportCampaignNegativeKeyword* to *ReportCampaignNegativeKeywords* (also notice the 's' after *Keyword*)
Also change all *ReportKeyword* to *ReportKeywords*.

Same thing in : server/server/src/main/java/com/google/api/ads/adwords/awreporting/server/util/StorageHelper.java with ReportCampaignNegativeKeyword and ReportKeyword to ReportCampaignNegativeKeywords and ReportKeywords.

Hope it helps :)

**Comment by chenzhuo914** [comment]
Will take a look later this week. :)
