### ISSUE TITLE
OAuth: unable (clumsy) entering code

### ISSUE THREAD

**Issue by gggerd** [googleads/aw-reporting#157]
Hi aw-reporting Team !

When trying to enter the code I get from https://accounts.google.com/o/oauth2/approval after pasting the given URL in the browser the following error occurs:

**ACTION REQUIRED** Paste this url in your browser and authenticate using your **AdWords Admin Email**:

https://accounts.google.com/o/oauth2/auth?access_type=offline&approval_prompt=force&client_id=xxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com&redirect_uri=urn:ietf:wg:oauth:2.0:oob&response_type=code&scope=https://adwords.google.com/api/adwords

Type the code you received on the web page here:
3/S1KCjyJ-BijwGIU-X0AVNwYgQAi-lm0J2qs-ns6G_wg
-bash: 3/S1KCjyJ-BijwGIU-X0AVNwYgQAi-lm0J2qs-ns6G_wg: No such file or directory

[11]+  Stopped                 java -Xmx4G -jar /home/aw-reporting/target/aw-reporting.jar -startDate 20150715 -endDate 20150720 -file /home/aw-report.properties -verbose -debug

And I can't remember what did the trick when installing last time...

I use putty as console program & right click to insert the code.
After pressing ENTER the error above occurs.

Thank Your for your help in advance!

Regards,
gggerd

**Comment by gustavo-moreira** [comment]
Hi,

I believe that the Ctrl+C to copy the code is killing aw-reporting on the background.
Could you try right clicking and then select "Copy" with the code selected?

Att.

**Comment by gggerd** [comment]
Hi gustavo

thanks for the speedy reply!

in putty (http://goo.gl/PxVJZe) there is no need to press "ctrl+c" for copying something. you just have to mark the lines and that's it. the marked content gets copied automatically. getting the URL from putty and pasting it to the browser is not a problem as well as copying the token from the browser and pasting it back to putty.

aw-reporting stops as soon as I press RETURN after inserting the token/code

Thanks,
gggerd

**Comment by gggerd** [comment]
Update:

I now tried entering the code manually - same result.
As soon as I press RETURN the script stops working with the eroor message posted above.
Any Idea ?

Thanks
gggerd

**Comment by gggerd** [comment]
SOLVED:

I ran the command as background process:

```
$ java -Xmx1G -jar aw-reporting/target/aw-reporting.jar -startDate YYYYMMDD -endDate YYYYMMDD \
-file aw-reporting/src/main/resources/aw-report-sample.properties -verbose &
```
Therefore entering the code returned by https://accounts.google.com/o/oauth2 was not possible.
Sorry for being muddle-headed...

Thanks!
gggerd
