### ISSUE TITLE
a different object with the same identifier value was already associated with the session

### ISSUE THREAD

**Issue by gggerd** [googleads/aw-reporting#159]
Hi !

as using the Geo-Report functionality the first time I get the following error:

```
2015-08-03 17:49:19,494 [ERROR|com.google.api.ads.adwords.awreporting.processors.onmemory.RunnableProcessorOnMemory|RunnableProcessorOnMemory] Error processing report for account: 2032484923 a different object with the same identifier value was already associated with the session: [com.google.api.ads.adwords.awreporting.model.entities.ReportGeo#2032484923-253723444-39441932404-23154705-20555731-2303-203421]
org.hibernate.NonUniqueObjectException: a different object with the same identifier value was already associated with the session: [com.google.api.ads.adwords.awreporting.model.entities.ReportGeo#2032484923-253723444-39441932404-23154705-20555731-2303-203421]
```

Currently I am not able to figure out the consequences since the job is being executed nevertheless and there is data in the 'aw_reportgeo' table as well (I don't know if its all the data).

Any idea or explanation?

Thanks!
gggerd

**Comment by gustavo-moreira** [comment]
Hi,

the Geo report has a "hidden" segment that is breaking AwReporting right now, by not allowing us to create a unique ID for the row. We are waiting for a fix on the API side so we can again support this report.
Besides playing around the segment fields to find a combination that works, unfortunately there is nothing else that can be done.

Att.

**Comment by chenzhuo914** [comment]
Well I tried Geo Performance Report with the default fields in the properties file, and it worked fine, so I guess that "hidden" segment is not always causing problem.

Gggerd, would you please also check what are the SEGMENT fields you have selected to pull the report data, and make sure that ALL these segment fields' values are added in the setId() function of com.google.api.ads.adwords.awreporting.model.entities.ReportGeo. This would ensure generating different ids for different report entries (though the "hidden" segment that Gustavo mentioned still can defeat it). I think it worths to verify setId(), just in case the hidden segment is not the real culprit of your problem. :)

**Comment by gggerd** [comment]
Hi

I tried with all segment fields' values added (and let the other configuration unchanged) with no change regarding to the error I stated in my first post.

While strolling through the console output I recognized two more errors:

<table style="border-collapse:collapse"><tr><td>org.hibernate.NonUniqueObjectException: a different object with the same identifier value was already associated with the session: [com.google.api.ads.adwords.awreporting.model.entities.<strong>ReportKeywords</strong> #null-2015-07-01-2015-07-01]</td></tr></table>

as well as

<table style="border-collapse:collapse"><tr><td>HTTP Response Code: 400, FieldPath: ConversionTrackerId, Trigger: Cannot select a combination of ConversionTrackerId and AverageCpc,AverageCpm,AveragePosition,Clic            ks,Cost,Ctr,Impressions, Type: ReportDefinitionError.INVALID_FIELD_NAME_FOR_REPORT</td></tr></table>

As they do not disappear when disabling Geo Performance Report I assume there are some more issues within other types of reports as well?

Thanks,
gggerd

**Comment by chenzhuo914** [comment]
> HTTP Response Code: 400, FieldPath: ConversionTrackerId, Trigger: Cannot select a combination of ConversionTrackerId and AverageCpc,AverageCpm,AveragePosition,Clic ks,Cost,Ctr,Impressions, Type: ReportDefinitionError.INVALID_FIELD_NAME_FOR_REPORT

The error message is pretty concrete - your selected fields combination is not supported. In other words, "ConversionTrackerId" field is not compatible with "AverageCpc" etc and cannot be downloaded together. You can get such information in our reports documents. For example for Geo Performance Report, check https://developers.google.com/adwords/api/docs/appendix/reports/geo-performance-report#conversiontrackerid (click the toggle button with text "Not compatible with the following fields").

**Comment by gggerd** [comment]
Hi Guys

any update on the "Geo report" hidden fields issue? 

Thanks!

gggerd

**Comment by gustavo-moreira** [comment]
We are reworking the ID generation logic, and how we match the report description in the API. This issue will be covered by that.
