### ISSUE TITLE
Cannot process Kratus

### ISSUE THREAD

**Issue by spospy** [googleads/aw-reporting#160]
java -Xmx4G -jar aw-reporting-server.jar -processKratus -startDate 20150801 -endDate 20150809 -file ../kratubackend.properties

 *\* Generating Kratus (for: 3067) **
index: { "v" : 1 , "key" : { "_id" : 1} , "name" : "_id_" , "ns" : "AdWordsReports.com.google.api.ads.adwords.awreporting.server.entities.Kratu"}
index: { "v" : 1 , "key" : { "externalCustomerId" : 1 , "day" : 1} , "name" : "externalCustomerId_1_day_1" , "ns" : "AdWordsReports.com.google.api.ads.adwords.awreporting.server.entities.Kratu"}

log4j:WARN No appenders could be found for logger (org.springframework.core.env.StandardEnvironment).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
java.lang.NullPointerException
        at com.google.api.ads.adwords.awreporting.server.kratu.KratuCompute.createDailyKratuFromDB(KratuCompute.java:269)
        at com.google.api.ads.adwords.awreporting.server.kratu.RunnableKratu.run(RunnableKratu.java:87)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by gustavo-moreira** [comment]
Joel, I imagine that this is just missing a check for null, but does this affect the generated reports?

**Comment by chenzhuo914** [comment]
We will be removing the server modules in v2 release, please refer to [this blog post](http://googleadsdeveloper.blogspot.com/2017/01/upcoming-changes-to-awreporting.html) for details and feedback.

**Comment by chenzhuo914** [comment]
We've just released v2.0.0, with all server modules removed.
