### ISSUE TITLE
includeZeroImpressions=false ignored for Keyword report

### ISSUE THREAD

**Issue by praflo** [googleads/aw-reporting#162]
Hello,
I have set this in properties file:

aw.report.definition.includeZeroImpressions=false

it works for account,campaign,adgroup and ads, but not for keyword report as I get a lot of zero impressions rows in AW_ReportKeywords table.

Applies to aw-reporting version cloned on 2015-08-12.

**Comment by chenzhuo914** [comment]
Hi praflo, it seems I cannot reproduce the problem on my account. With "aw.report.definition.includeZeroImpressions=false", my keywords performance report doesn't contain any zero impressions rows.

Could you give more details so we can look at your issue?
- What's the Account ID
- What's the report you are downloading (is it KEYWORDS_PERFORMANCE_REPORT)?
- What fields you are downloading?
- What's the time range?

**Comment by praflo** [comment]
Hello,
See below.

On 18/08/2015 08:01, chenzhuo914 wrote:
>
> Hi praflo, it seems I cannot reproduce the problem on my account. With 
> "aw.report.definition.includeZeroImpressions=false", my keywords 
> performance report doesn't contain any zero impressions rows.
>
> Could you give more details so we can look at your issue?
>
>   * What's the Account ID
>
it happens with all Accont IDs in MCC. Try this for example: 3811249627
>
>   * What's the report you are downloading (is it
>     KEYWORDS_PERFORMANCE_REPORT)?
>
KEYWORDS_PERFORMANCE_REPORT
>
>   * What fields you are downloading?
>
KEYWORDS_PERFORMANCE_REPORT=ExternalCustomerId,Month,AccountDescriptiveName,Cost,Clicks,Impressions,Conversions,Ctr,AverageCpm,AverageCpc,AveragePosition,AccountCurrencyCode,Id,QualityScore,KeywordMatchType,KeywordText,DestinationUrl,AdGroupId,AdGroupName,CampaignId,Status,IsNegative,CampaignName,SearchExactMatchImpressionShare,SearchImpressionShare,SearchRankLostImpressionShare,ConversionsManyPerClick,ConversionRateManyPerClick,CostPerConversionManyPerClick,ConvertedClicks,ClickConversionRate,CostPerConvertedClick,CpcBid,Criteria

Other parameters in properties config file:
aw.report.processor.type=ONMEMORY
aw.report.processor.rows.size=1000
aw.report.processor.threads=14
aw.report.downloader.num.threads=20
aw.report.downloader.retries.count=5
aw.report.downloader.backoff.interval=5000
aw.report.downloader.buffer.size=0x1000
aw.report.definition.includeZeroImpressions=false

>   * What's the time range?
>
java -Xmx1G -jar aw-reporting/target/aw-reporting.jar -startDate 
20150501  -endDate 20150731


After I run it, this is what I have in DB:

mysql> select MONTH,count(*) from AW_ReportKeyword where 
ACCOUNT_ID=3811249627 group by MONTH;
+---------------------+----------+
| MONTH               | count(*) |
+---------------------+----------+
| 2015-05-01 14:00:00 |      180 |
| 2015-06-01 14:00:00 |      176 |
+---------------------+----------+
2 rows in set (0.00 sec)

mysql> select MONTH,count(*) from AW_ReportKeyword where 
ACCOUNT_ID=3811249627 and IMPRESSIONS=0 group by MONTH;
+---------------------+----------+
| MONTH               | count(*) |
+---------------------+----------+
| 2015-05-01 14:00:00 |       10 |
| 2015-06-01 14:00:00 |       22 |
+---------------------+----------+
2 rows in set (0.00 sec)


It applies to DAY segment as well

**Comment by chenzhuo914** [comment]
Hi praflo, thanks for providing all the details, and yes I can reproduce it now.

This is not caused by aw-reporting, but AdWords API behaviour. I have reported this issue to AdWords API engineers, and will let you know if there's any update.

**Comment by chenzhuo914** [comment]
Hi praflo, it turns out that includeZeroImpressions controls all selected stats instead of just "Impressions" field. For your case, although some rows has Impressions=0, but other *ImpressionShare fields are non zero, so they are still returned. If you remove those *ImpressionShare fields, such rows would be dropped when includeZeroImpressions=false.

**Comment by praflo** [comment]
Ok, thank you.
