### ISSUE TITLE
Error parsing the values for the command line options: Unrecognized option: -generatePdf

### ISSUE THREAD

**Issue by rraborg** [googleads/aw-reporting#164]
Hi,
I installed java, maven, mysql, builded the project using maven, configured MySQL database and configured AwReporting.
I can download data from our AdWords account, I see database populated, but when I execute the command:

java -Xmx1G -jar aw-reporting.jar -generatePdf <htmlTemplateFile> <outputDirectory> -startDate YYYYMMDD -endDate YYYYMMDD -file <file>

I receive the following error message:

Error parsing the values for the command line options: Unrecognized option: -generatePdf  

Is not recognizing flag "-generatePfd"

Server information is:
- CentOS release 6.6 (Final)
- Linux version 2.6.32-504.el6.i686

Java Information is:
- java version "1.7.0_79"
- Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
- Java HotSpot(TM) Client VM (build 24.79-b02, mixed mode)

Please advice,
Thank you,
Regards,

Roque.

**Comment by chenzhuo914** [comment]
Hi Roque, actually we used to have a "generatePdf" option, but we removed the functionality later as we think it's not perfect yet. We may release a separate project on PDF generation, but don't have a timeline to share for now.

I will update the readme file to remove "generatePdf" as well.

**Comment by rraborg** [comment]
Thanks for your answer.
Is there any template file in any known format that can replace the PDF template?
I had a PDF template ready to try.
Please advice,
Regards,
Roque.

**Comment by chenzhuo914** [comment]
Unfortunately not for now. :(
