### ISSUE TITLE
Conversions column in mongodb always set to zero

### ISSUE THREAD

**Issue by spospy** [googleads/aw-reporting#165]
I have made a fresh install with the latest version of the code. When running the download followed by processing of the Kratus, the conversions column is always set to zero even for days on which conversions occurred. This is the same for all accounts I have tested.

e.g 
java -Xmx4G -jar aw-reporting-server.jar -startDate 20150814 -endDate 20150818 -file ../kratu.backend.properties

then,

java -Xmx4G -jar aw-reporting-server.jar -processKratus -startDate 20150814 -endDate 20150818 -file ../kratu.backend.properties

There are no errors in either of the above when run in verbose mode.

But when querying the mongodb the conversions data is always zero.

e.g. 
db.getCollection("com.google.api.ads.adwords.awreporting.server.entities.Kratu").find({accountName: { $in: ["an account name"] }, day: {$gte:"20150816"}}, {accountName:1, day:1, conversions:1})

{ "_id" : "9371916627-20150816", "accountName" : "an account name", "day" : "20150816", "conversions" : 0 }
{ "_id" : "9371916627-20150817", "accountName" : "an account name", "day" : "20150817", "conversions" : 0 }
etc

**Comment by chenzhuo914** [comment]
Gues sit

**Comment by chenzhuo914** [comment]
Guess it's the same issue as #167? Please check my comments there, and provide more details if you think it's another issue.

**Comment by chenzhuo914** [comment]
I'm closing this bug since there's no reply for a while, please feel free to reopen it.
