### ISSUE TITLE
URLs on AdGroup Level

### ISSUE THREAD

**Issue by gggerd** [googleads/aw-reporting#170]
Hi all

I'm stuck...
Since Upgraded URLs have been introduced I can't figure out how to receive URLs on AdGroup level (in former days easily by aw_reportad.DESTINATION_URL).

Within the CRITERIA_PERFORMANCE_REPORT I only can see URLs for Keyword, User List, Placement, Mobile App Category, Vertical and Product Partition.
```
CRITERIA_PERFORMANCE_REPORT=ExternalCustomerId,CampaignId,AdGroupId,Id,CriteriaType,Criteria,CriteriaDestinationUrl,Impressions,Clicks,Cost
```

Within DESTINATION_URL_REPORT I only get a few results of old (inactive) ads...
```
DESTINATION_URL_REPORT=ExternalCustomerId,CampaignId,AdGroupId,AdGroupName,EffectiveDestinationUrl
```

Any hint is appreciated, thanks for your efforts in advance!

gggerd

**Comment by chenzhuo914** [comment]
Updated URL related fields are available in various reports. For example, in CRITERIA_PERFORMANCE_REPORT they are:
FinalUrls, FinalMobileUrls, FinalAppUrls, TrackingUrlTemplate, UrlCustomParameters

In AD_PERFORMANCE_REPORT, they are:
CreativeFinalUrls, CreativeFinalMobileUrls, CreativeFinalAppUrls, CreativeTrackingUrlTemplate, CreativeUrlCustomParameters

DESTINATION_URL_REPORT is for old Destination Urls before Upgraded Url, so it does not contain any Upgraded Url fields.

**Comment by amirlazarovich** [comment]
You can also use the FINAL_URL_REPORT. It includes statistics aggregated at the final URL level, one row per final URL
