### ISSUE TITLE
click type valid or non valid

### ISSUE THREAD

**Issue by gezimapi** [googleads/aw-reporting#179]
hi how can i detect if a click is valid or no?

**Comment by chenzhuo914** [comment]
Hi gezimapi, what's you definition of validity of clicks?

If it means legitimate traffic, actually AdWords will try to filter all [invalid clicks] (https://support.google.com/adwords/answer/42995) at background, so there should be only valid clicks in the reports. You can also [troubleshoot invalid clicks] (https://support.google.com/adwords/troubleshooter/2557048) when you have any concern / suspicion.

**Comment by chenzhuo914** [comment]
Closing this issue since there's no reply for 15 days. Please feel free to reopen if necessary.
