### ISSUE TITLE
Erro in create code

### ISSUE THREAD

**Issue by garbim** [googleads/aw-reporting#184]
I trying use AWReport in other account, but in create code in terminal return this error

2015-09-16 18:03:59,612 [ERROR|com.google.api.ads.adwords.awreporting.authentica
tion.InstalledOAuth2Authenticator|InstalledOAuth2Authenticator] Error Authentica
ting: An error occured obtaining the OAuth2Credential
com.google.api.ads.common.lib.exception.OAuthException: An error occured obtaini
ng the OAuth2Credential
        at com.google.api.ads.adwords.awreporting.authentication.InstalledOAuth2
Authenticator.getNewOAuth2Credential(InstalledOAuth2Authenticator.java:224)
        at com.google.api.ads.adwords.awreporting.authentication.InstalledOAuth2
Authenticator.getOAuth2Credential(InstalledOAuth2Authenticator.java:149)
        at com.google.api.ads.adwords.awreporting.authentication.InstalledOAuth2
Authenticator.authenticate(InstalledOAuth2Authenticator.java:91)
        at com.google.api.ads.adwords.awreporting.processors.ReportProcessor.ret
rieveAccountIds(ReportProcessor.java:104)
        at com.google.api.ads.adwords.awreporting.processors.onmemory.ReportProc
essorOnMemory.generateReportsForMCC(ReportProcessorOnMemory.java:108)
        at com.google.api.ads.adwords.awreporting.AwReporting.main(AwReporting.j
ava:205)
2015-09-16 18:03:59,614 [ERROR|com.google.api.ads.adwords.awreporting.AwReportin
g|AwReporting] Unexpected error accessing the API: An error occured obtaining th
e OAuth2Credential
com.google.api.ads.common.lib.exception.OAuthException: An error occured obtaini
ng the OAuth2Credential
        at com.google.api.ads.adwords.awreporting.authentication.InstalledOAuth2
Authenticator.getNewOAuth2Credential(InstalledOAuth2Authenticator.java:224)
        at com.google.api.ads.adwords.awreporting.authentication.InstalledOAuth2
Authenticator.getOAuth2Credential(InstalledOAuth2Authenticator.java:149)
        at com.google.api.ads.adwords.awreporting.authentication.InstalledOAuth2
Authenticator.authenticate(InstalledOAuth2Authenticator.java:91)
        at com.google.api.ads.adwords.awreporting.processors.ReportProcessor.ret
rieveAccountIds(ReportProcessor.java:104)
        at com.google.api.ads.adwords.awreporting.processors.onmemory.ReportProc
essorOnMemory.generateReportsForMCC(ReportProcessorOnMemory.java:108)
        at com.google.api.ads.adwords.awreporting.AwReporting.main(AwReporting.j
ava:205)

My developer token is one account and i create clientId and clientSecret for other google account, for conect mccAccountId in other account, its is a problem ?

**Comment by gustavo-moreira** [comment]
Hi,

You can use the developer token with any account. Did you change the MCC id in the properties file?
Seems like AwReporting is trying to access the old MCC with the new credentials.
Att.

**Comment by chenzhuo914** [comment]
Closing this issue since there's no reply for 22 days. Please feel free to reopen if necessary.
