### ISSUE TITLE
Insertion of the field "Estimated Total Conversions" in the report

### ISSUE THREAD

**Issue by fernandacaroline2008** [googleads/aw-reporting#197]
I need the insertion of the field "Estimated Total Conversions" in the report because it is required in the RMF
Thank you..

**Comment by chenzhuo914** [comment]
This field will be removed in the new v201509 (see [here] (https://developers.google.com/adwords/api/docs/reference/#conversion-reporting)). We will make sure to add all the "AllConversions*" fields instead when upgrading to v201509.

**Comment by gustavo-moreira** [comment]
This was added in the new version.
