### ISSUE TITLE
Error : ERROR [RunnableProcessorOnMemory] Error processing report for account: XXXXXXXXXXX 502

### ISSUE THREAD

**Issue by ashishodia** [googleads/aw-reporting#199]
Hi Team,

We are using these API for downloading the different reports from Adwords. However, there are some account IDs, where we are getting below errors:

ERROR [RunnableProcessorOnMemory] Error processing report for account: XXXXXXXXXX 502
ERROR [RunnableProcessorOnMemory] Error processing report for account: XXXXXXXXXX 502
ERROR [RunnableProcessorOnMemory] Error processing report for account: XXXXXXXXXX 502
ERROR [RunnableProcessorOnMemory] Error processing report for account: XXXXXXXXXX 502
ERROR [RunnableProcessorOnMemory] Error processing report for account: XXXXXXXXXX 502
ERROR [RunnableProcessorOnMemory] Error processing report for account: XXXXXXXXXX 502
ERROR [RunnableProcessorOnMemory] Error processing report for account: XXXXXXXXXX 502
ERROR [RunnableProcessorOnMemory] Error processing report for account: XXXXXXXXXX 502
ERROR [RunnableProcessorOnMemory] Error processing report for account: XXXXXXXXXX 502

Could you please look into this and suggest us, where the problem is?

Many thanks in advance for your support.

Ankur

**Comment by gustavo-moreira** [comment]
Hi,

could you send us more details about the errors, like for example the report types and configurations?

Thanks.

**Comment by chenzhuo914** [comment]
Closing for now since there's no response for a while. Feel free to reopen it when necessary.
