### ISSUE TITLE
Upgrade to Java7

### ISSUE THREAD

**Issue by allisongreene** [googleads/aw-reporting#212]
Some other libraries that should be updated/reviewed include:

Spring (3.2.2.RELEASE  --> 4.2.3.RELEASE)
Google-Client (1.17.0-rc --> 1.21.0)
org.apache.commons (removed - replaced with groupId commons-io)
commons-io (1.3.2 --> 2.4)
commons-cli (1.2 --> 1.3.1)
commons-configuration (1.7 --> 1.10)
guava-jdk5 (removed)
guava  (16.0-rc1  --> either 18.0 or 19.0-rc2)

**Comment by chenzhuo914** [comment]
We can update the libs, but let's hold the Java7 upgrade. If we decide that aw-reporting becomes an extension of Java client library, it should be on Java6 until client library upgrades to 7.

**Comment by gustavo-moreira** [comment]
Let's go with the update of the libraries then, and leave Java7 for the next time we do this.
Thanks.

**Comment by chenzhuo914** [comment]
It will be fixed in v2 release.

**Comment by chenzhuo914** [comment]
Done.
