### ISSUE TITLE
ReportAd processing download painfully slow

### ISSUE THREAD

**Issue by Jaccib3006** [googleads/aw-reporting#223]
Hi,

The latest version of aw reporting was downloaded to a new directory, clean install for both aw-reporitng and aw-reporting-server etc.  
Ran the following command to download the data:
java -Xmx4G -jar aw-reporting-server.jar -startDate 20160122 –endDate 20160127 -file ../kratubackend.properties –verbose

Ran for over 18+ hours but never got past the generating the ReportAd, records were inserted into all the collections but only 300ish in the ReportAd collection. 

Indexing problem on ReportAd collection?

Tried rerunning the reports and now have following message
nothing in error log but screen shows:

Generating: ACCOUNT_PERFORMANCE_REPORT **
Downloading reports....
(Error: AuthorizationError.USER_PERMISSION_DENIED Trigger:null) 
2016-01-28 14:25:51..

**Comment by chenzhuo914** [comment]
Hi Jaccib, there's a fatal API error in the console output:
> (Error: AuthorizationError.USER_PERMISSION_DENIED Trigger:null) 

Please refer to the explanation of the error at [this doc page](https://developers.google.com/adwords/api/docs/common-errors#AuthorizationError), and double check whether the developerToken / mccAccountId / clientId / clientSecret fields are correct in the properties file.

**Comment by Jaccib3006** [comment]
Purge, download and rebuild seems to have sorted the issue

**Comment by Jaccib3006** [comment]
Hi,

Apologies I should have given a little more detail, the error only occurred on the Account_Performance_Report, all other reports ran OK

Did a full purge/download/rebuild and everything appears to be working now, fingers crossed.

Thanks

Jacci

**Comment by chenzhuo914** [comment]
Cool! Thanks for your effort on using aw-reporting and filing bugs to help improve it. Please feel free to reopen / create new issues when you encounter any problem. :)
