### ISSUE TITLE
Typo in AW_ReportKeywords table?

### ISSUE THREAD

**Issue by praflo** [googleads/aw-reporting#235]
In AW_ReportKeywords there is a column called "SEARCH_PREDICATED_CTR". I think it should be "SEARCH_PREDICTED_CTR" instead.

(https://developers.google.com/adwords/api/docs/appendix/reports/keywords-performance-report#searchpredictedctr)

**Comment by chenzhuo914** [comment]
Good catch, thanks! Fixed in 887feeb117aa982594c7819a5ef407853650bad5.
