### ISSUE TITLE
Missing DevicePreference in Ad report?

### ISSUE THREAD

**Issue by praflo** [googleads/aw-reporting#239]
Hello,
Is there any reason why the DevicePreference (https://developers.google.com/adwords/api/docs/appendix/reports/ad-performance-report#devicepreference) attribute for AD report is not included?
I could not find any matching field in AW_ReportAd table, nor it seems to be declared in any config or java file.

thank you
gian

**Comment by chenzhuo914** [comment]
Hi Gian,

Yes, the DevicePreference attribute is missing in the [ReportAd.java](https://github.com/googleads/aw-reporting/blob/master/aw-reporting-model/src/main/java/com/google/api/ads/adwords/awreporting/model/entities/ReportAd.java). As a temporary workaround, would you please add it yourself into the above Java file (after all, this is a open-source project)? We are working on a central effort to make up all the missing reports and fields, after that you won't encounter such problems any more.

Regards,
Zhuo
