### ISSUE TITLE
awReporting for v201607 ?

### ISSUE THREAD

**Issue by Timmeh74** [googleads/aw-reporting#248]
Hi!
Will there be an updated release for v201607, seeing that v201605 has been skipped ?

Regards,
Tim

**Comment by chenzhuo914** [comment]
Hi Tim,

Yes there will be. Recently we are busy with other priorities, so the upgrading gets delayed. But we will definitely upgrade it before v201603 sunsets.

Thanks and regards,
Zhuo

**Comment by Timmeh74** [comment]
Hi Zhou,

thanks for the update. I'll be patient then ;)

Regards,
Tim
