### ISSUE TITLE
sample.properties files are incomplete

### ISSUE THREAD

**Issue by Smartsasse** [googleads/aw-reporting#255]
Now when upgrading to 201607 I wanted to get data into the following new columns "HEADLINE_PART1", "HEADLINE_PART2" and "DESCRIPTION". 

When looking through the project I found the following two files which lists all properties I should be able to get, but they don't seem to be up to date since they don't mention the above columns.

aw-reporting/target/classes/aw-report-sample-properties
aw-reporting/src/main/resources/aw-report-sample.properties

However, adding "HeadlinePart1, HeadlinePart2, Description" to the end of the following line in the properties file solves the problem.
AD_PERFORMANCE_REPORT=

So, the issue I'm reporting is that the sample files doesn't seem to be up to date. Or is the information of which columns I can include documented somewhere else?

**Comment by chenzhuo914** [comment]
Thanks for filing this issue, but it's Work As Intended - actually we think it doesn't worth the effort to keep all available fields up-to-date in the properties file - after all they are just comments.

You can find the complete list of supported report fields in the corresponding Java entity file, for AD_PERFORMANCE_REPORT it's [ReportAd.java](https://github.com/googleads/aw-reporting/blob/master/aw-reporting-model/src/main/java/com/google/api/ads/adwords/awreporting/model/entities/ReportAd.java). Just look at all @CsvField/reportField values. You can also check the official documentation for [Ad Performance Report](https://developers.google.com/adwords/api/docs/appendix/reports/ad-performance-report), and look at all the field names in the left column of the long table, as well as the right panel of the page.
