### ISSUE TITLE
files missing?

### ISSUE THREAD

**Issue by AndrewBrock** [googleads/aw-reporting#259]
Hello,

I would like to update the aw-reporting tool to the latest google ads api verion, however when I pull the latest release it seems like some files are missing. For example when i look in aw-reporting/aw-reporting/target the directory is no longer there. Could you advise if the files are missing, or if I'm looking in the wrong repo for this project?

Thanks,
Andy

![image](https://cloud.githubusercontent.com/assets/11057198/19809558/24671064-9d2a-11e6-840c-98b97866b090.png)

**Comment by chenzhuo914** [comment]
Hi Andy,

The "target" folders are for build output (e.g., *.class files), which shouldn't be included in the github repo.  If you look at ".gitignore" file, you will see that "target" folders are deliberately ignored.

If you run "mvn compile" or "mvn install", you will see "target" folders being generated. :)

Regards,
Zhuo
