### ISSUE TITLE
aw-reporting.jar not found after project is built

### ISSUE THREAD

**Issue by daviptch** [googleads/aw-reporting#260]
Hi,

I am updating v201603 aw-reporting to v201609, but I can't find aw-reporting/target/aw-reporting.jar after project is compiled (see image the build of aw-reporting). I did the same steps with the other versions in the past and they worked fine. Has something changed or is that something I am missing?

Thanks and kind regards.

![mvn_build_aw-reporting](https://cloud.githubusercontent.com/assets/6670215/19879678/46c5c32c-a030-11e6-93fc-0c758675d369.png)

**Comment by chenzhuo914** [comment]
Hi there,

I tried to pull the project and mvn install it, and it successfully generates aw-reporting.jar in ./aw-reporting/target folder.

Which exact maven command did you run? Could you try the following ones as instructed in README:
mvn clean install eclipse:eclipse
mvn compile dependency:copy-dependencies package

Regards,
Zhuo

**Comment by daviptch** [comment]
Thanks for returning me. I retried all over again and it worked. Copied and pasted your 'mvn compile' to run it just to be sure.

Thanks again.
