### ISSUE TITLE
How to get keywordReport Data for search impressions?

### ISSUE THREAD

**Issue by Webmasterei** [googleads/aw-reporting#263]
Hi,
I'm evaluating data at the moment. 
So I am calling with:
    `command = 'java -Xmx1G -jar ../aw-reporting/aw-reporting/target/aw-reporting.jar -startDate ' + date_start + ' -endDate ' + date_end + ' -file ../aw-reporting/aw-reporting/src/main/resources/aw-report-sample.properties -accountIdsFile ../accounts.csv'`

to get report data. This works fine so far but I'm not getting any data on search impression share and other values which are not reported for small numbers. 

My timespan is 30 days, so my data is sufficent. I think the reason is that the reporting tool pulls data for each day instead of data for a timespan.

How can I get timespan data, so there are values for this kind of attributes?

**Comment by chenzhuo914** [comment]
Hi there, please check your "aw-report-sample.properties" file, for the "KEYWORDS_PERFORMANCE_REPORT=..." config line, make sure that:
1. it includes "SearchImpressionShare" filed name
1. it does not include any time-related fields such as "Date", "Month", etc - in this way the report will be aggregated for the timespan of your "-startDate" and "-endDate" values.

In fact we don't recommend #<span>2</span>: you should download each day's report data to keep the history, and aggregate (such as via SQL) them each time according to your specified timespan.

**Comment by chenzhuo914** [comment]
Closing for now as there's no more follow up, please feel free to reopen if necessary.
