### ISSUE TITLE
How to get campaign level info by sending campaignIds?

### ISSUE THREAD

**Issue by eshwarchettri02** [googleads/aw-reporting#265]
Hi,
  I'am currently using adword's aw-reporting for reports, I want to know that whether we can send the campaign Ids to get the campaign information(Manaul Synchronization) through Aw-reporting?

**Comment by chenzhuo914** [comment]
Could you elaborate on what kind of campaign information you want to retrieve? I also don't understand what do you mean by "Manual Synchronization".

Basically, aw-reporting can only retrieve report data, and does not support selecting a subset of entities through some filtering conditions, although you could download all data and choose your interested ones from database records.
