### ISSUE TITLE
Remove "verbose" command line option from Readme

### ISSUE THREAD

**Issue by hakimio** [googleads/aw-reporting#267]
"Readme" has to be updated to reflect the removal of "verbose" command line option. If you try to run the command as shown in the Readme, you'll get an error.

**Comment by chenzhuo914** [comment]
Hi hakimio, thanks for reporting this! You are right, we will fix it in next release.

**Comment by nwbirnie** [comment]
Fixed in 31f6c817e93865329239b03c15322c6552b167f2
