### ISSUE TITLE
aw.report.processor.threads still doesn't reflect database insertion threads

### ISSUE THREAD

**Issue by robtro** [googleads/aw-reporting#270]
It (still) appears that the thread configuration does not reflect or configure the database insertion component of reporting processing. 

I can light up all 64 cores on one of my more powerful servers during the report **DOWNLOAD** stage, but once the database insertion begins, the maximum concurrent insertion processes never climbs above 2 or 3. 

This was something we were working together on in the last (2013-2015) but was left off in favor of your time migrating to the newer version of aw-reporting. 

Could we re-visit this? Makes no sense to go ballistic downloading, only to bottleneck at the insertion part :)

**Comment by chenzhuo914** [comment]
Hi robtro, sorry I wasn't aware of previous discussions, but per my understanding of the internal logic:

- If you choose "aw.report.processor.type=FILE" in config: for each report type, it will use "aw.report.downloader.num.threads" # of threads to download reports (one thread per account), save all report files in temporary folder, then use "aw.report.processor.threads" # of threads to process them (one thread per report file) by parsing report data and persisting it into database.

- If you choose "aw.report.processor.type=STREAM" in config: for each report type, it will use "aw.report.processor.threads" # of threads to download AND process reports (one thread per account to download file + process report data from stream on the fly). The "aw.report.downloader.num.threads" setting is not used at all in this option.

I guess you are using "FILE" processing type - could you confirm that? Could you try to use "STREAM" and see what's the behavior?

Also, for "FILE" type, at "processing" step, it solely depends on the system to create threads (Executors.newFixedThreadPool()), and the hibernate framework to persist data into database, but NOT directly manage thread utilization at all. Would you please also check if you database setting has any limit on simultaneous connections?

**Comment by robtro** [comment]
1. We've been using STREAM (onmemory) for a while now. 
2. As for the MySQL server, no, there are no limits on the amount of simultaneous connections or. This server has 64 multi-threaded cores, for a total of 128, 512GB of RAM... it's a quite powerful server. No limits exist and some testing to prove the database can handle hundreds of sim. connections was done just to make sure. 

The thing is... regardless of what setting is used, the mySQL connections never seem to rise above 2-3. If they truly were processed in the same thread they were downloaded with, we'd see hundreds of connections because during the download process every single core/processor is lit up to 100%.  

Is there anything you can point me to? I'm willing to do any experiments you think might be valuable.
