### ISSUE TITLE
Database Schema Change (maximum breaking changes)

### ISSUE THREAD

**Issue by robtro** [googleads/aw-reporting#273]
I would like to see the option to NOT be forced to totally change my database schema when doing something simple such as migrating to a new AdWords API version. 

Why, once again, are the database table names and column names changing? With changes that massive, there's a lot of work involved for developers that have software written to utilize this software as a backend. 

Is my only option to directly edit files like this: aw-reporting/aw-reporting-model/src/main/java/com/google/api/ads/adwords/awreporting/model/entities/AccountPerformanceReport.java, and recompile?

**Comment by robtro** [comment]
Anything?

**Comment by allisongreene** [comment]
Hi,

The database schema is based on the latest report definition, so there may be some schema changes when updating between AdWords API versions. You can always check the release notes (https://developers.google.com/adwords/api/docs/reference/#reporting) prior to updating to verify the changes.

If you would like to use your own table or column schema, you can modify the entity classes as you mentioned and then recompile.

Best,
Allison

**Comment by robtro** [comment]
Where on that page does it say that the entire database schema was dumped and rewritten? I can't find it anywhere.

**Comment by robtro** [comment]
And, why was this removed? This is actually a useful function: 
`(mvn hibernate4:export -Phbm2ddl)`

![image](https://user-images.githubusercontent.com/2265292/27482920-e17df068-57e8-11e7-8d53-b85a3a8ec573.png)

**Comment by allisongreene** [comment]
Hi,

Apologies, but I thought you were referring to the latest API version update (from v201702 to v201705). It seems you are referring to when we released version 2.0 of AwReporting.  We posted the upcoming changes in our Ads Developer Blog (http://googleadsdeveloper.blogspot.com/) and linked to the blog post in GitHub page several months ago.  Additionally, our change log (https://github.com/googleads/aw-reporting/blob/master/ChangeLog.md) lists the database schema changes.  Please make sure you follow the Ads Developer Blog (http://googleadsdeveloper.blogspot.com/) for future changes.

We removed the hibernate export to simplify the code a bit. I think there is a workaround to pull schema from the database directly, such as: https://stackoverflow.com/questions/1498777/how-do-i-show-the-schema-of-a-table-in-a-mysql-database  Please let me know if this will work for you.

Best,
Allison

**Comment by robtro** [comment]
I know how to view the schema of my own existing databases. 

The purpose of the old hibernate export code was to show the NEW schema generated by aw-reporting. This way you can clearly view the proposed database changes prior to any upgrades, and plan accordingly.
