### ISSUE TITLE
DATE fields in NEW SCHEMA INCORRECT.

### ISSUE THREAD

**Issue by robtro** [googleads/aw-reporting#274]
With this recent complete overhaul of the aw-reporting database schema, it appears that the DATE (Date) fields are incorrectly declared as VARCHAR instead of DATETIME as it used to be. 

I am going to assume this was done in error, as there's no logical reason to change the date field to varchar from the correct declaration of "DATETIME"

**Comment by allisongreene** [comment]
Hi,

Date is a String values represented as yyyy-MM-dd or enum values.

Best,
Allison

**Comment by robtro** [comment]
Date (Day) was always a "DATETIME" field in the SQL configuration. Check all the previous revisions of this software, it's always been a Date column, not VARCHAR/String. 

I understand you need DATE as a STRING for the ROW_ID generator, but for the database column itself, if it's not correctly implemented as a DATE/DATETIME field, software that's been built on top of the aw-reporting project will have errors running queries based on these tables with incorrectly configured date columns. 

I'll do it myself, but, per your last message about altering the entities files and recompiling - I'm not seeing any changes. To test the most simple of changes, I tried this in AccountPerformanceReport.java: 

```
/**
   * Specific report class for AccountPerformanceReport.
 *
*/
@Entity
@Table(name = "AW_AccountPerformanceReportB")
@CsvReport(value = ReportDefinitionReportType.ACCOUNT_PERFORMANCE_REPORT)
```

Note the change to "AW_AccountPerformanceReportB" - my question is, why dont these changes reflect once compiled? 

In "DateReport.java" I created an additional function to return the Date as a Date object, along with yours that returns it as a string - but still, nothing is working that way after recompilation. Ideas?

**Comment by robtro** [comment]
https://github.com/googleads/aw-reporting/pull/275

Easy fix for the date field
