### ISSUE TITLE
RunnableProcessorOnMemory

### ISSUE THREAD

**Issue by mofa** [googleads/aw-reporting#276]
I suddenly started getting the below error for all the accounts:

ERROR [RunnableProcessorOnMemory] Error processing report for account:

How can I solve it?

**Comment by nwbirnie** [comment]
Closing this issue due to lack of information. If this recurs feel free to reopen the issue with the error trace.

Additionally, you could try running with -Xmx1024m (or higher) to allocate a larger heap.
