### ISSUE TITLE
Improvement request: abort if account ids file is empty

### ISSUE THREAD

**Issue by muhlegg** [googleads/aw-reporting#283]
It seems that the tool fetches every single account under the selected MCC if the account ids file is empty. Luckily we noticed it in the logs before several thousands of account ALL_TIME daily data was downloaded. I guess nobody really wants it to fetch all accounts if a accounts file is specified in the options.

**Comment by nwbirnie** [comment]
Hi and thanks for your feature request. This seems like a good addition and reasonably expected behavior. I'll aim to resolve this in the next release cycle (next couple of months).

**Comment by nwbirnie** [comment]
Included in the latest release of AW Reporting. Please update when ready.
