### ISSUE TITLE
accountIdsFile specify manager accounts 

### ISSUE THREAD

**Issue by mofa** [googleads/aw-reporting#293]
Can we specify manager accounts (MCC) in the accountIdsFile or should it necessarily be the lowest child accounts only?

**Comment by nwbirnie** [comment]
You cannot specify manager accounts in the accountIdsFile.

**Comment by mofa** [comment]
Okay. Another thing is there a template for how the accountIdsFile should look like?

**Comment by nwbirnie** [comment]
The account Ids file should have one line per account ID. These may optionally include the dashes like XXX-XXX-XXXX or without dashes like XXXXXXXXXX.

Blank lines and lines starting with # are ignored.
