### ISSUE TITLE
below error when running the AwReporting.java

### ISSUE THREAD

**Issue by taigeun-kim** [googleads/aw-reporting#297]
Hi,
I am getting the below error when running the AwReporting.java with my information Specified at aw-report-sample.properties.
(like managerAccountId, developerToken, ClientID and ClientSecret)

This error occured during make refreshtoken maybe.

Could you let me know how do I solve this please?

I have no idea about this error.

**[[arguments]]**
-startDate 20181001
-endDate 20181002
-file C:\project\workspace\aw-reporting-master\aw-reporting\src\main\resources\aw-report-sample.properties
-onFileReport CAMPAIGN_PERFORMANCE_REPORT

[AwReporting_log.txt](https://github.com/googleads/aw-reporting/files/2662676/AwReporting_log.txt)

**Comment by nwbirnie** [comment]
It would appear that you have a truststore configured for your Java installation. This contains information about the SSL certificates and authorities that your application trusts. By default, this is configured by the JVM to include common sources of trusted certificates. However if you define your own trust store, this will not necessarily include the Google CA and related certificates.

You can locate your key/trust store by running your application with `-Djavax.net.debug=SSL,trustmanager` which should print a line like: `trustStore is: <path to trust store>`.

Then obtain the root certificates for our OAuth endpoints by visiting these URLs in your browser, opening the SSL dialog, and downloading the certificates for all the certificates in the path.

- [https://www.googleapis.com](https://www.googleapis.com)
- [https://accounts.google.com](https://accounts.google.com)

For example, in Chrome, viewing the certificates for Github looks like this:

![CA viewer](https://user-images.githubusercontent.com/410275/49730017-fb72b180-fc6e-11e8-9b8b-9d21458bae58.png)

Select the certificate authority (CA) certificates and click export. You can then use these with [keytool](https://docs.oracle.com/javase/8/docs/technotes/tools/windows/keytool.html) to import into your truststore.
