### ISSUE TITLE
AW_AdPerformanceReport does not exisit

### ISSUE THREAD

**Issue by gezimapi** [googleads/aw-reporting#301]
hi 

in the new version the AW_AdPerformanceReport table has not been created.

i created it from an older version but a lot of colums doesnt existis,

can u suply one with all colums.

Thx in advance

**Comment by Raibaz** [comment]
Hi,

Are you seeing any exceptions being printed out on application startup, i.e., during table creation?

**Comment by gezimapi** [comment]
hi , 

No where , everything seems Ok. But when add the table from an older version add the new fields seems that the max row length exceeded that allowed innodb table. So i changed some column length so now seems ok. 

Thx
