### ISSUE TITLE
Retrieve list Customer Ids under top customer

### ISSUE THREAD

**Issue by Jaccib3006** [googleads/aw-reporting#305]
Hi, we have a number of sub customer ids under our main customer id and are looking for some way of identifying which External Customer Ids are in each of the sub customer ids via the API, is this possible? 
Currently to obtain this information we have to go into each MCC under our Main Customer id and then go to Performance to see the Accounts under the Direct Manager then download to csv. Long winded way to obtain a list of Accounts under each direct manager, is there an easier way? Thanks Jacci

**Comment by nwbirnie** [comment]
Hey, sorry I missed this issue; you can retrieve the list of customers under a manager account by using [ManagedCustomerService](https://developers.google.com/adwords/api/docs/reference/v201809/ManagedCustomerService) directly. Please see this [Java example code](https://github.com/googleads/googleads-java-lib/blob/master/examples/adwords_axis/src/main/java/adwords/axis/v201809/accountmanagement/GetAccountHierarchy.java) for more details.
