### ISSUE TITLE
Upgrading from v201402

### ISSUE THREAD

**Issue by TMEFRT** [googleads/aw-reporting#98]
Hello Friends,

 I been using the software program from couple of months, and starting from nov18th, I started seeing exceptions in the logs,

(Error: RequestError.INVALID_INPUT Trigger:You are accessing an AdWords API version v201402 that has been discontinued. Calls to this version may fail. Please visit the AdWords API blog for information on migration to the new AdWords API version.)

Today I upgraded to the latest version, and executed the program, Exceptions disappeared from the logs,but data in the tables is not getting updated.  Please suggest if we need to follow any special steps to upgrade

-tmeft.

**Comment by gustavo-moreira** [comment]
Hi TMEFRT,

Did the update work?

Cheers.
